<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartServiceSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('part_services')->truncate();

        $rows = [
            // =========================================================================
            // 1. DUMP TRUCK - FUSO FIGHTER FN62 (SESUAI DOKUMEN ASLI LAMPIRAN PENGGUNA)
            // =========================================================================
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'ENGINE OIL',
                'part_number' => 'SAE 15W-40',
                'ps_250' => null,
                'ps_500' => 13,
                'ps_1000' => 13,
                'ps_2000' => 13,
                'ps_4000' => 13,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli mesin pelumas utama diesel',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'OIL TRANSMISI',
                'part_number' => 'SAE 80W-90',
                'ps_250' => null,
                'ps_500' => 9,
                'ps_1000' => 9,
                'ps_2000' => 9,
                'ps_4000' => 9,
                'category' => 'Lubricant & Oil',
                'notes' => 'Gearbox transmission fluid',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'OIL TRANSMISI',
                'part_number' => 'SAE 80W-90',
                'ps_250' => null,
                'ps_500' => 22,
                'ps_1000' => 22,
                'ps_2000' => 22,
                'ps_4000' => 22,
                'category' => 'Lubricant & Oil',
                'notes' => 'Pelumas transfer case & auxiliary',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'OIL DIFFERENTIAL',
                'part_number' => 'SAE 80W-140',
                'ps_250' => null,
                'ps_500' => 22,
                'ps_1000' => 22,
                'ps_2000' => 22,
                'ps_4000' => 22,
                'category' => 'Lubricant & Oil',
                'notes' => 'Gardan tandem gardan belakang',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'STEERING HYDRAULIC OIL',
                'part_number' => 'ATF Dexron III',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => null,
                'ps_4000' => 2,
                'category' => 'Lubricant & Oil',
                'notes' => 'Minyak power steering kemudi',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'HYDRAULIC OIL',
                'part_number' => 'ISO VG 46',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 5,
                'ps_2000' => 5,
                'ps_4000' => 15,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli hidrolik dump hoist cylinder',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'ENGINE OIL FILTER',
                'part_number' => 'ME130968IDN',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan oli mesin utama',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FUEL FILTER',
                'part_number' => 'KM005852',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan bahan bakar solar',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FILTER RACOR',
                'part_number' => 'KM005035',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Pemisah air solar Racor water separator',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FUEL FILTER',
                'part_number' => 'KM006110A1',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan solar sekunder',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'AIR CLEANER OUTER',
                'part_number' => 'ME073821IDN',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara primer luar',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'AIR CLEANER INNER',
                'part_number' => 'ME291563IDN',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara pengaman dalam',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FILTER STEERING',
                'part_number' => 'MC090385',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli power steering',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'ELEMENT KIT,PCV VALVE',
                'part_number' => 'ME302763',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => null,
                'ps_4000' => 1,
                'category' => 'Engine Parts',
                'notes' => 'Katup ventilasi karter mesin',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FAN BELT ALTERNATOR',
                'part_number' => 'ME300899IDN',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 3,
                'ps_4000' => 3,
                'category' => 'Belt & Drive',
                'notes' => 'Tali kipas alternator & kipas mesin (3 pcs)',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'FAN AC',
                'part_number' => 'A-39',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Belt & Drive',
                'notes' => 'Tali v-belt kompresor pendingin AC kabin',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'BOTTLE SAMPLE OIL ENGINE',
                'part_number' => 'HP-427',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji lab oli mesin SOS (Scheduled Oil Sampling)',
            ],
            [
                'equipment' => 'DUMP TRUCK 10 RODA',
                'model' => 'FUSO FIGHTER FN62',
                'unit_type' => 'DT',
                'part_name' => 'BOTTLE SAMPLE OIL NON ENGINE',
                'part_number' => 'HP-426',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji lab oli transmisi/differential SOS',
            ],

            // =========================================================================
            // 2. DUMP TRUCK - SHACMAN F3000 (SESUAI MASTER UNIT & PLAN: DT-3011 s/d DT-3019)
            // =========================================================================
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'ENGINE OIL WEICHAI WP12',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 32,
                'ps_500' => 32,
                'ps_1000' => 32,
                'ps_2000' => 32,
                'ps_4000' => 32,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas carter oli mesin WP12 (32 Liter)',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'TRANSMISSION OIL FAST GEAR',
                'part_number' => 'SAE 85W-90 GL-5',
                'ps_250' => null,
                'ps_500' => 14,
                'ps_1000' => 14,
                'ps_2000' => 14,
                'ps_4000' => 14,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli gearbox Fast 12JSD160T (14 Liter)',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'DIFFERENTIAL OIL REAR TANDEM',
                'part_number' => 'SAE 85W-140 GL-5',
                'ps_250' => null,
                'ps_500' => 28,
                'ps_1000' => 28,
                'ps_2000' => 28,
                'ps_4000' => 28,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli gardan tandem MAN 16T (14L + 14L)',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'STEERING & HOIST HYDRAULIC OIL',
                'part_number' => 'ISO VG 46 / ATF',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 24,
                'ps_2000' => 24,
                'ps_4000' => 24,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli silinder dump hoist & power steering',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'ENGINE OIL FILTER WEICHAI',
                'part_number' => '61000070005',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin Weichai asli',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'FUEL FILTER PRIMARY WATER SEPARATOR',
                'part_number' => '612600081335',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar primer pemisah air',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'FUEL FILTER SECONDARY FINE',
                'part_number' => '612600081334',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar sekunder halus',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'AIR CLEANER OUTER PRIMARY',
                'part_number' => 'DZ9118190230',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara luar tabung besar',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'AIR CLEANER INNER SAFETY',
                'part_number' => 'DZ9118190231',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara dalam pengaman',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'FAN BELT ALTERNATOR 8PK',
                'part_number' => '8PK1440',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Belt & Drive',
                'notes' => 'Tali kipas alternator serpentine belt',
            ],
            [
                'equipment' => 'DUMP TRUCK',
                'model' => 'SHACMAN F3000',
                'unit_type' => 'DT',
                'part_name' => 'BOTTLE SAMPLE OIL ENGINE SOS',
                'part_number' => 'HP-427',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji laboratorium SOS oli mesin',
            ],

            // =========================================================================
            // 3. EXCAVATOR - CAT 320 GX & CAT 330 GX (SESUAI MASTER UNIT: EX-205, EX-309..311)
            // =========================================================================
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'ENGINE OIL CAT C7.1',
                'part_number' => 'SAE 15W-40 CK-4',
                'ps_250' => 32,
                'ps_500' => 32,
                'ps_1000' => 32,
                'ps_2000' => 32,
                'ps_4000' => 32,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter mesin C7.1 ACERT (32 Liter)',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'ENGINE OIL FILTER ULTRA HIGH EFFICIENCY',
                'part_number' => '1R-1808',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin efisiensi tinggi Cat Asli',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'FUEL FILTER PRIMARY (WATER SEPARATOR)',
                'part_number' => '326-1644',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Pemisah air solar dengan mangkok drain',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'FUEL FILTER SECONDARY',
                'part_number' => '1R-0770',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar sekunder presisi 4 micron',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'HYDRAULIC OIL HIGH PRESSURE',
                'part_number' => 'ISO VG 46 / HYDO ADVANCED',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 280,
                'ps_4000' => 280,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras total oli hidrolik tangki dan sistem kerja (280 Liter)',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'HYDRAULIC PILOT FILTER',
                'part_number' => '093-7521',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter sirkuit joystick pilot control',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'HYDRAULIC RETURN FILTER',
                'part_number' => '126-1817',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli hidrolik balik ke tangki',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'SWING MACHINERY GEAR OIL',
                'part_number' => 'SAE 85W-140',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 14,
                'ps_2000' => 14,
                'ps_4000' => 14,
                'category' => 'Lubricant & Oil',
                'notes' => 'Pelumas gearbox swing drive unit (14 Liter)',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'FINAL DRIVE TRAVEL GEAR OIL',
                'part_number' => 'SAE 85W-140',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 18,
                'ps_2000' => 18,
                'ps_4000' => 18,
                'category' => 'Lubricant & Oil',
                'notes' => 'Pelumas travel final drive kiri & kanan (9L + 9L)',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'AIR CLEANER OUTER',
                'part_number' => '245-6375',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Elemen saringan udara luar',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'AIR CLEANER INNER',
                'part_number' => '245-6376',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Elemen pengaman saringan udara dalam',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'AIR CONDITIONER FILTER CABIN',
                'part_number' => '293-1184',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter sirkulasi AC kabin operator',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'BOTTLE SAMPLE OIL ENGINE SOS',
                'part_number' => 'HP-427',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji laboratorium SOS oli mesin',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'CAT 320 GX / 330 GX',
                'unit_type' => 'EXCA',
                'part_name' => 'BOTTLE SAMPLE OIL HYDRAULIC SOS',
                'part_number' => 'HP-426',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji laboratorium SOS oli hidrolik',
            ],

            // =========================================================================
            // 4. EXCAVATOR - SANY SY330H (SESUAI MASTER UNIT: EX-302, EX-304, EX-305)
            // =========================================================================
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'ENGINE OIL ISUZU 6HK1',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 36,
                'ps_500' => 36,
                'ps_1000' => 36,
                'ps_2000' => 36,
                'ps_4000' => 36,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter mesin Isuzu 6HK1 (36 Liter)',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'ENGINE OIL FILTER SANY',
                'part_number' => '60133177',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin Sany genuine',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'FUEL PRE-FILTER WATER SEPARATOR',
                'part_number' => '60031766',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar primer pemisah air',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'FUEL FINE FILTER MAIN',
                'part_number' => '60031767',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar sekunder halus',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'HYDRAULIC RETURN FILTER SANY',
                'part_number' => '60036814',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli hidrolik tangki balik',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'AIR CLEANER OUTER',
                'part_number' => '60134444',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara primer luar',
            ],
            [
                'equipment' => 'EXCAVATOR',
                'model' => 'SANY SY330H',
                'unit_type' => 'EXCA',
                'part_name' => 'AIR CLEANER INNER',
                'part_number' => '60134445',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara pengaman dalam',
            ],

            // =========================================================================
            // 5. BULLDOZER - CAT D8 GC (SESUAI MASTER UNIT: DZ-007, DZ-008, DZ-010)
            // =========================================================================
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL CAT 3406C',
                'part_number' => 'SAE 15W-40 CK-4',
                'ps_250' => 38,
                'ps_500' => 38,
                'ps_1000' => 38,
                'ps_2000' => 38,
                'ps_4000' => 38,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli mesin Cat 3406C / C15 (38 Liter)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL FILTER CAT (2 PCS)',
                'part_number' => '1R-0716',
                'ps_250' => 2,
                'ps_500' => 2,
                'ps_1000' => 2,
                'ps_2000' => 2,
                'ps_4000' => 2,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin ganti 2 buah per servis',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'FUEL FILTER PRIMARY (WATER SEPARATOR)',
                'part_number' => '1R-0770',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Pemisah air bahan bakar solar primer',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'FUEL FILTER SECONDARY',
                'part_number' => '1R-0749',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan bahan bakar solar halus 2 micron',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'TRANSMISSION & TORQFLOW OIL',
                'part_number' => 'TO-4 SAE 30',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 120,
                'ps_2000' => 120,
                'ps_4000' => 120,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras total oli transmisi power shift torqflow (120L)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'TRANSMISSION FILTER',
                'part_number' => '1G-8878',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter pelumasan transmisi torqflow',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'FINAL DRIVE OIL (LH/RH)',
                'part_number' => 'TO-4 SAE 50',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 68,
                'ps_2000' => 68,
                'ps_4000' => 68,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras oli final drive kiri dan kanan (34L + 34L)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'BEVEL GEAR & STEERING CLUTCH OIL',
                'part_number' => 'TO-4 SAE 30',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 95,
                'ps_2000' => 95,
                'ps_4000' => 95,
                'category' => 'Lubricant & Oil',
                'notes' => 'Pelumas rumah gigi kerucut & kopling kemudi (95L)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'HYDRAULIC OIL (BLADE & RIPPER)',
                'part_number' => 'ISO VG 46 / HYDO',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 110,
                'ps_4000' => 110,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras total oli hidrolik silinder blade & ripper',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'HYDRAULIC RETURN FILTER',
                'part_number' => '1R-0777',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter sirkulasi balik tangki hidrolik',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'AIR CLEANER OUTER',
                'part_number' => '4N-0015',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara primer luar',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'AIR CLEANER INNER',
                'part_number' => '4N-0016',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara pengaman dalam',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'FAN BELT SET',
                'part_number' => '9L-6644',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Belt & Drive',
                'notes' => 'Tali kipas pendingin radiator set',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'BOTTLE SAMPLE OIL ENGINE SOS',
                'part_number' => 'HP-427',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji lab oli mesin SOS',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'CAT D8 GC',
                'unit_type' => 'DOZER',
                'part_name' => 'BOTTLE SAMPLE OIL TRANSMISI SOS',
                'part_number' => 'HP-426',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Consumable & Lab',
                'notes' => 'Botol uji lab oli transmisi torqflow SOS',
            ],

            // =========================================================================
            // 6. BULLDOZER - SEM 822D (SESUAI MASTER UNIT: DZ-005, DZ-012)
            // =========================================================================
            [
                'equipment' => 'BULLDOZER',
                'model' => 'SEM 822D',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL WEICHAI WP12',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 34,
                'ps_500' => 34,
                'ps_1000' => 34,
                'ps_2000' => 34,
                'ps_4000' => 34,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter mesin Weichai WP12 (34 Liter)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'SEM 822D',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL FILTER',
                'part_number' => 'W950/31',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin utama',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'SEM 822D',
                'unit_type' => 'DOZER',
                'part_name' => 'FUEL PRE-FILTER WATER SEPARATOR',
                'part_number' => 'PL420',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar primer dengan sensor air',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'SEM 822D',
                'unit_type' => 'DOZER',
                'part_name' => 'HYDROSTATIC HYDRAULIC OIL',
                'part_number' => 'ISO VG 46 / 68',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 140,
                'ps_4000' => 140,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras oli sistem penggerak hidrostatis ganda',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'SEM 822D',
                'unit_type' => 'DOZER',
                'part_name' => 'HYDROSTATIC HIGH PRESSURE FILTER',
                'part_number' => 'W-15-00040',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli hidrostatis tekanan tinggi',
            ],

            // =========================================================================
            // 7. BULLDOZER - ZOOMLION ZD-320-3 (SESUAI MASTER UNIT: DZ-002, DZ-069)
            // =========================================================================
            [
                'equipment' => 'BULLDOZER',
                'model' => 'ZOOMLION ZD-320-3',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL CUMMINS NTA855',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 45,
                'ps_500' => 45,
                'ps_1000' => 45,
                'ps_2000' => 45,
                'ps_4000' => 45,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter Cummins NTA855 (45 Liter)',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'ZOOMLION ZD-320-3',
                'unit_type' => 'DOZER',
                'part_name' => 'ENGINE OIL FILTER (2 PCS)',
                'part_number' => 'LF9009',
                'ps_250' => 2,
                'ps_500' => 2,
                'ps_1000' => 2,
                'ps_2000' => 2,
                'ps_4000' => 2,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin kombinasi bypass Cummins',
            ],
            [
                'equipment' => 'BULLDOZER',
                'model' => 'ZOOMLION ZD-320-3',
                'unit_type' => 'DOZER',
                'part_name' => 'FUEL FILTER WATER SEPARATOR',
                'part_number' => 'FS1000',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar primer pemisah air Fleetguard',
            ],

            // =========================================================================
            // 8. WHEEL LOADER - SEM 660D (SESUAI MASTER UNIT: WL-010)
            // =========================================================================
            [
                'equipment' => 'WHEEL LOADER',
                'model' => 'SEM 660D',
                'unit_type' => 'LOADER',
                'part_name' => 'ENGINE OIL WEICHAI WP10',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 22,
                'ps_500' => 22,
                'ps_1000' => 22,
                'ps_2000' => 22,
                'ps_4000' => 22,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter mesin loader 6 ton (22 Liter)',
            ],
            [
                'equipment' => 'WHEEL LOADER',
                'model' => 'SEM 660D',
                'unit_type' => 'LOADER',
                'part_name' => 'ENGINE OIL FILTER',
                'part_number' => '1000424655',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin Weichai',
            ],
            [
                'equipment' => 'WHEEL LOADER',
                'model' => 'SEM 660D',
                'unit_type' => 'LOADER',
                'part_name' => 'FUEL FILTER PRIMARY',
                'part_number' => '612600081335',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar primer pemisah air',
            ],
            [
                'equipment' => 'WHEEL LOADER',
                'model' => 'SEM 660D',
                'unit_type' => 'LOADER',
                'part_name' => 'TRANSMISSION TORQUE CONVERTER OIL',
                'part_number' => 'TO-4 SAE 30',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => 45,
                'ps_2000' => 45,
                'ps_4000' => 45,
                'category' => 'Lubricant & Oil',
                'notes' => 'Oli transmisi powershift TR200',
            ],
            [
                'equipment' => 'WHEEL LOADER',
                'model' => 'SEM 660D',
                'unit_type' => 'LOADER',
                'part_name' => 'HYDRAULIC OIL (BUCKET & STEERING)',
                'part_number' => 'ISO VG 46',
                'ps_250' => null,
                'ps_500' => null,
                'ps_1000' => null,
                'ps_2000' => 170,
                'ps_4000' => 170,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kuras total tangki oli hidrolik bucket (170 Liter)',
            ],

            // =========================================================================
            // 9. SUPPORT TRUCK - QUESTER CWE 280 (SESUAI MASTER UNIT: WT-009, WT-011)
            // =========================================================================
            [
                'equipment' => 'WATER TRUCK 20.000 KL',
                'model' => 'QUESTER CWE 280',
                'unit_type' => 'SUPPORT',
                'part_name' => 'ENGINE OIL UD TRUCKS GH8E',
                'part_number' => 'SAE 15W-40 CI-4',
                'ps_250' => 28,
                'ps_500' => 28,
                'ps_1000' => 28,
                'ps_2000' => 28,
                'ps_4000' => 28,
                'category' => 'Lubricant & Oil',
                'notes' => 'Kapasitas oli carter mesin GH8E (28 Liter)',
            ],
            [
                'equipment' => 'WATER TRUCK 20.000 KL',
                'model' => 'QUESTER CWE 280',
                'unit_type' => 'SUPPORT',
                'part_name' => 'ENGINE OIL FILTER',
                'part_number' => '21707133',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter oli mesin utama UD Trucks',
            ],
            [
                'equipment' => 'WATER TRUCK 20.000 KL',
                'model' => 'QUESTER CWE 280',
                'unit_type' => 'SUPPORT',
                'part_name' => 'FUEL PRE-FILTER WATER SEPARATOR',
                'part_number' => '20998367',
                'ps_250' => 1,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Pemisah air bahan bakar solar primer',
            ],
            [
                'equipment' => 'WATER TRUCK 20.000 KL',
                'model' => 'QUESTER CWE 280',
                'unit_type' => 'SUPPORT',
                'part_name' => 'FUEL FINE FILTER SECONDARY',
                'part_number' => '21380475',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Filter solar sekunder halus',
            ],
            [
                'equipment' => 'WATER TRUCK 20.000 KL',
                'model' => 'QUESTER CWE 280',
                'unit_type' => 'SUPPORT',
                'part_name' => 'AIR CLEANER OUTER',
                'part_number' => '21834205',
                'ps_250' => null,
                'ps_500' => 1,
                'ps_1000' => 1,
                'ps_2000' => 1,
                'ps_4000' => 1,
                'category' => 'Filter',
                'notes' => 'Saringan udara primer luar',
            ],
        ];

        $now = now();
        foreach ($rows as &$r) {
            $r['created_at'] = $now;
            $r['updated_at'] = $now;
        }

        DB::table('part_services')->insert($rows);
    }
}
