<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PpuRecord;

class PpuRecordSeeder extends Seeder
{
    public function run(): void
    {
        PpuRecord::truncate();

        $records = [
            [
                'unit_no' => 'DZ-002',
                'model' => 'ZOOMLION ZD-320-3',
                'track_group_used' => 'BERCO (ITALY)',
                'cts_date' => '2026-09-02',
                'last_fitted_track_group' => '2025-11-10',
                'pct_hours_track' => 34.5,
                'hours_track_gp' => 2850,
                'smu' => 8398,
                'sprocket_lh' => 45.2,
                'sprocket_rh' => 44.8,
                'link_height_lh' => 138.5,
                'link_height_rh' => 137.9,
                'chain_bushing_lh' => 74.2,
                'chain_bushing_rh' => 74.0,
                'frame_ext_lh' => 12.0,
                'frame_ext_rh' => 11.5,
                'grouser_height_lh' => 58.0,
                'grouser_height_rh' => 57.5,
                'idler_front_lh' => 21.0,
                'idler_front_rh' => 20.8,
                'idler_rear_lh' => 20.5,
                'idler_rear_rh' => 20.2,
                'inspection_date' => '2026-09-02',
                'inspector' => 'Andi Herwan (PMC)',
                'notes' => 'Keausan undercarriage 34.5% normal. Ketegangan rantai sesuai spesifikasi pabrik.',
                'status' => 'NORMAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'DZ-005',
                'model' => 'SEM 822D',
                'track_group_used' => 'CATERPILLAR (TU)',
                'cts_date' => '2026-09-03',
                'last_fitted_track_group' => '2025-08-15',
                'pct_hours_track' => 46.2,
                'hours_track_gp' => 3450,
                'smu' => 7269,
                'sprocket_lh' => 42.0,
                'sprocket_rh' => 41.5,
                'link_height_lh' => 132.0,
                'link_height_rh' => 131.5,
                'chain_bushing_lh' => 71.5,
                'chain_bushing_rh' => 71.0,
                'frame_ext_lh' => 15.0,
                'frame_ext_rh' => 14.5,
                'grouser_height_lh' => 52.0,
                'grouser_height_rh' => 51.5,
                'idler_front_lh' => 19.5,
                'idler_front_rh' => 19.0,
                'idler_rear_lh' => 19.0,
                'idler_rear_rh' => 18.8,
                'inspection_date' => '2026-09-03',
                'inspector' => 'Hariadi (GM & Mgr. Maintenance)',
                'notes' => 'Sprocket segment masih bagus, keausan merata pada track link kiri dan kanan.',
                'status' => 'NORMAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'DZ-007',
                'model' => 'CAT D8 GC',
                'track_group_used' => 'CATERPILLAR HEAVY DUTY',
                'cts_date' => '2026-09-01',
                'last_fitted_track_group' => '2024-04-12',
                'pct_hours_track' => 78.4,
                'hours_track_gp' => 5800,
                'smu' => 11842,
                'sprocket_lh' => 36.5,
                'sprocket_rh' => 35.8,
                'link_height_lh' => 124.0,
                'link_height_rh' => 123.2,
                'chain_bushing_lh' => 66.0,
                'chain_bushing_rh' => 65.5,
                'frame_ext_lh' => 24.5,
                'frame_ext_rh' => 25.0,
                'grouser_height_lh' => 41.0,
                'grouser_height_rh' => 40.5,
                'idler_front_lh' => 16.0,
                'idler_front_rh' => 15.5,
                'idler_rear_lh' => 15.8,
                'idler_rear_rh' => 15.2,
                'inspection_date' => '2026-09-01',
                'inspector' => 'Hariadi (GM & Mgr. Maintenance)',
                'notes' => 'PERHATIAN: Track adjuster bocor dan chain bushing mencapai 78.4% wear. Rantai kendor saat ripping.',
                'status' => 'CAUTION',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'DZ-008',
                'model' => 'CAT D8 GC',
                'track_group_used' => 'CATERPILLAR HEAVY DUTY',
                'cts_date' => '2026-09-05',
                'last_fitted_track_group' => '2026-01-20',
                'pct_hours_track' => 28.0,
                'hours_track_gp' => 1850,
                'smu' => 11665,
                'sprocket_lh' => 46.5,
                'sprocket_rh' => 46.0,
                'link_height_lh' => 139.0,
                'link_height_rh' => 138.8,
                'chain_bushing_lh' => 75.0,
                'chain_bushing_rh' => 74.8,
                'frame_ext_lh' => 10.5,
                'frame_ext_rh' => 10.0,
                'grouser_height_lh' => 60.5,
                'grouser_height_rh' => 60.0,
                'idler_front_lh' => 22.0,
                'idler_front_rh' => 21.8,
                'idler_rear_lh' => 21.5,
                'idler_rear_rh' => 21.2,
                'inspection_date' => '2026-09-05',
                'inspector' => 'Hariadi (GM & Mgr. Maintenance)',
                'notes' => 'Track group baru dipasang awal tahun, kondisi sangat prima.',
                'status' => 'NORMAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'DZ-010',
                'model' => 'CAT D8 GC',
                'track_group_used' => 'ITM (HHI)',
                'cts_date' => '2026-09-06',
                'last_fitted_track_group' => '2024-02-18',
                'pct_hours_track' => 88.6,
                'hours_track_gp' => 6200,
                'smu' => 9307,
                'sprocket_lh' => 33.2,
                'sprocket_rh' => 34.0,
                'link_height_lh' => 119.5,
                'link_height_rh' => 121.0,
                'chain_bushing_lh' => 62.8,
                'chain_bushing_rh' => 63.5,
                'frame_ext_lh' => 28.0,
                'frame_ext_rh' => 27.5,
                'grouser_height_lh' => 37.0,
                'grouser_height_rh' => 38.0,
                'idler_front_lh' => 14.5,
                'idler_front_rh' => 15.0,
                'idler_rear_lh' => 14.8,
                'idler_rear_rh' => 15.2,
                'inspection_date' => '2026-09-06',
                'inspector' => 'Andi Herwan (PMC)',
                'notes' => 'KRITIS: Sprocket segment tajam dan link height mendekati batas limit. Segera jadwalkan pergantian track group bersamaan servis PM.',
                'status' => 'CRITICAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'EX-205',
                'model' => 'CAT 320 GX',
                'track_group_used' => 'CATERPILLAR OEM',
                'cts_date' => '2026-09-01',
                'last_fitted_track_group' => '2025-12-01',
                'pct_hours_track' => 22.0,
                'hours_track_gp' => 1450,
                'smu' => 4330,
                'sprocket_lh' => 48.0,
                'sprocket_rh' => 47.8,
                'link_height_lh' => 142.0,
                'link_height_rh' => 141.5,
                'chain_bushing_lh' => 76.5,
                'chain_bushing_rh' => 76.2,
                'frame_ext_lh' => 8.5,
                'frame_ext_rh' => 8.0,
                'grouser_height_lh' => 64.0,
                'grouser_height_rh' => 63.5,
                'idler_front_lh' => 23.0,
                'idler_front_rh' => 22.8,
                'idler_rear_lh' => 22.5,
                'idler_rear_rh' => 22.2,
                'inspection_date' => '2026-09-01',
                'inspector' => 'Andi Herwan (PMC)',
                'notes' => 'Undercarriage kondisi sangat baik, tidak ada kelonggaran pin atau bushing.',
                'status' => 'NORMAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'EX-302',
                'model' => 'SANY SY330H',
                'track_group_used' => 'SANY OEM',
                'cts_date' => '2026-09-03',
                'last_fitted_track_group' => '2025-06-10',
                'pct_hours_track' => 39.5,
                'hours_track_gp' => 2600,
                'smu' => 3906,
                'sprocket_lh' => 44.5,
                'sprocket_rh' => 44.0,
                'link_height_lh' => 135.5,
                'link_height_rh' => 135.0,
                'chain_bushing_lh' => 73.0,
                'chain_bushing_rh' => 72.8,
                'frame_ext_lh' => 13.0,
                'frame_ext_rh' => 12.5,
                'grouser_height_lh' => 55.0,
                'grouser_height_rh' => 54.5,
                'idler_front_lh' => 20.5,
                'idler_front_rh' => 20.0,
                'idler_rear_lh' => 20.0,
                'idler_rear_rh' => 19.8,
                'inspection_date' => '2026-09-03',
                'inspector' => 'Andi Herwan (PMC)',
                'notes' => 'Kondisi undercarriage stabil, keausan wajar sesuai jam kerja.',
                'status' => 'NORMAL',
                'created_by' => 'Planner CTS'
            ],
            [
                'unit_no' => 'EX-305',
                'model' => 'SANY SY330H',
                'track_group_used' => 'SANY OEM',
                'cts_date' => '2026-09-05',
                'last_fitted_track_group' => '2025-03-20',
                'pct_hours_track' => 64.8,
                'hours_track_gp' => 3800,
                'smu' => 2940,
                'sprocket_lh' => 39.0,
                'sprocket_rh' => 38.5,
                'link_height_lh' => 128.5,
                'link_height_rh' => 127.8,
                'chain_bushing_lh' => 69.2,
                'chain_bushing_rh' => 68.8,
                'frame_ext_lh' => 19.5,
                'frame_ext_rh' => 20.0,
                'grouser_height_lh' => 47.0,
                'grouser_height_rh' => 46.5,
                'idler_front_lh' => 18.0,
                'idler_front_rh' => 17.5,
                'idler_rear_lh' => 17.8,
                'idler_rear_rh' => 17.2,
                'inspection_date' => '2026-09-05',
                'inspector' => 'Andi Herwan (PMC)',
                'notes' => 'Ditemukan 8 baut track shoe kanan lepas (dibuatkan WO-011 & BL-010). Link height 64.8% wear.',
                'status' => 'CAUTION',
                'created_by' => 'Planner CTS'
            ]
        ];

        foreach ($records as $r) {
            PpuRecord::create($r);
        }
    }
}
