<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PsSchedule;
use App\Models\PsScheduleBacklog;
use App\Models\MasterEquip;
use App\Models\Backlog;
use App\Models\WorkOrder;
use App\Models\Inspection;
use App\Models\OilSample;
use App\Models\PpuRecord;
use App\Models\PmRecord;
use App\Models\FailureAnalysis;
use App\Models\DailyHm;
use App\Models\PlanService;

class PsScheduleSeeder extends Seeder
{
    public function run(): void
    {
        // Bersihkan tabel ps_schedules dan ps_schedule_backlogs
        PsScheduleBacklog::truncate();
        PsSchedule::truncate();

        // Tanggal target: 2026-09-25 (sesuai jam sistem WOSys ERP) dan 2024-09-25 (tanggal referensi spreadsheet)
        $targetDates = [
            date('Y-m-d'), // Tanggal sekarang (2026-09-25)
            '2024-09-25'   // Tanggal arsip spreadsheet
        ];

        // Definisi unit aktual yang dijadwalkan servis berkala beserta parameter operasionalnya
        $scheduleBlueprints = [
            // ==================== 1. CLUSTER: POWER PLANT ====================
            [
                'equip_no' => 'GST-003',
                'sub_section' => 'POWER PLANT',
                'pic' => 'AGUS R',
                'location' => 'KBCT',
                'plan_start_time' => '07:30',
                'est_hours' => 0.8,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0015',
                'notif_no' => '120004182272',
                'resrv_no' => '5800331',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44028',
                'ppa_ref' => 'PPA-GST03',
                'dms_ref' => 'FAR-2026-003',
                'ppm_ref' => null,
                'ppe_ref' => 'PPE-ALT-03',
                'ppc_ref' => null,
                'vis_ref' => null,
                'backlog_keys' => ['BL-005'],
            ],
            [
                'equip_no' => 'GST-004',
                'sub_section' => 'POWER PLANT',
                'pic' => 'AGUS R',
                'location' => 'KBCT',
                'plan_start_time' => '08:30',
                'est_hours' => 0.8,
                'ps_type' => '500',
                'wo_no' => '2201877406',
                'notif_no' => '120004205424',
                'resrv_no' => '5894896',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44029',
                'ppa_ref' => null,
                'dms_ref' => null,
                'ppm_ref' => 'PM-2615',
                'ppe_ref' => 'PPE-ACCU-04',
                'ppc_ref' => null,
                'vis_ref' => 'INSP-015',
                'backlog_keys' => [],
            ],

            // ==================== 2. CLUSTER: SUPPORT MEDIUM ====================
            [
                'equip_no' => 'EX-205',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '07:30',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0002',
                'notif_no' => '120004184379',
                'resrv_no' => '5897327',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44012',
                'ppa_ref' => 'PPA-EX205',
                'dms_ref' => 'BL-001',
                'ppm_ref' => 'PM-2609',
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-06',
                'vis_ref' => 'INSP-001',
                'backlog_keys' => ['BL-001'],
            ],
            [
                'equip_no' => 'DZ-002',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '07:30',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0006',
                'notif_no' => '120004183182',
                'resrv_no' => '5893321',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44014',
                'ppa_ref' => 'PPA-DZ002',
                'dms_ref' => null,
                'ppm_ref' => 'PM-2611',
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-01',
                'vis_ref' => 'INSP-005',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'DZ-005',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '08:00',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => '2201889850',
                'notif_no' => '120004184112',
                'resrv_no' => '5895412',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => null,
                'ppm_ref' => 'PM-2610',
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-02',
                'vis_ref' => 'INSP-010',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'DZ-007',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '08:30',
                'est_hours' => 6.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0001',
                'notif_no' => '120004185200',
                'resrv_no' => '5896011',
                'av_parts_percent' => 98.0,
                'pap_ref' => 'LAB-44031',
                'ppa_ref' => 'PPA-DZ007',
                'dms_ref' => 'FAR-2026-001',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-03',
                'vis_ref' => 'INSP-003',
                'backlog_keys' => ['BL-002'],
            ],
            [
                'equip_no' => 'DZ-010',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'LMP',
                'plan_start_time' => '09:00',
                'est_hours' => 6.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0017',
                'notif_no' => '120004185990',
                'resrv_no' => '5896880',
                'av_parts_percent' => 85.0,
                'pap_ref' => null,
                'ppa_ref' => 'PPA-DZ010',
                'dms_ref' => 'BL-013',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-05',
                'vis_ref' => 'INSP-025',
                'backlog_keys' => ['BL-013'],
            ],
            [
                'equip_no' => 'EX-302',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '09:30',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0007',
                'notif_no' => '120004186100',
                'resrv_no' => '5897120',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44016',
                'ppa_ref' => 'PPA-EX302',
                'dms_ref' => null,
                'ppm_ref' => null,
                'ppe_ref' => 'WO2609-0014',
                'ppc_ref' => 'PPU-07',
                'vis_ref' => 'INSP-009',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'EX-305',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '10:00',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0011',
                'notif_no' => '120004186450',
                'resrv_no' => '5897550',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => 'BL-010',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => 'PPU-08',
                'vis_ref' => 'INSP-016',
                'backlog_keys' => ['BL-010'],
            ],
            [
                'equip_no' => 'EX-310',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '10:30',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => '2201889862',
                'notif_no' => '120004187010',
                'resrv_no' => '5897990',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => null,
                'ppm_ref' => 'PM-2614',
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-013',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'EX-311',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '11:00',
                'est_hours' => 4.0,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0015',
                'notif_no' => '120004187420',
                'resrv_no' => '5898230',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => 'BL-012',
                'ppm_ref' => null,
                'ppe_ref' => 'WO2609-0015',
                'ppc_ref' => null,
                'vis_ref' => 'INSP-022',
                'backlog_keys' => ['BL-012'],
            ],
            [
                'equip_no' => 'WL-016',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '11:30',
                'est_hours' => 4.0,
                'ps_type' => '500',
                'wo_no' => 'WO2609-0003',
                'notif_no' => '120004187890',
                'resrv_no' => '5898650',
                'av_parts_percent' => 95.0,
                'pap_ref' => 'LAB-44018',
                'ppa_ref' => 'PPA-WL016',
                'dms_ref' => 'BL-003',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-004',
                'backlog_keys' => ['BL-003'],
            ],
            [
                'equip_no' => 'WL-019',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '13:00',
                'est_hours' => 5.0,
                'ps_type' => '500',
                'wo_no' => 'WO2609-0005',
                'notif_no' => '120004188340',
                'resrv_no' => '5899120',
                'av_parts_percent' => 90.0,
                'pap_ref' => 'LAB-44022',
                'ppa_ref' => 'PPA-WL019',
                'dms_ref' => 'FAR-2026-002',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-006',
                'backlog_keys' => ['BL-004', 'BL-014'],
            ],
            [
                'equip_no' => 'SL-100',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '14:00',
                'est_hours' => 2.5,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0008',
                'notif_no' => '120004188760',
                'resrv_no' => '5899540',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => 'BL-007',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-007',
                'backlog_keys' => ['BL-007'],
            ],
            [
                'equip_no' => 'SL-300',
                'sub_section' => 'SUPPORT MEDIUM',
                'pic' => 'INDRA S',
                'location' => 'KBCT',
                'plan_start_time' => '14:30',
                'est_hours' => 2.5,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0009',
                'notif_no' => '120004189120',
                'resrv_no' => '5899880',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => null,
                'ppm_ref' => 'PM-2617',
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-012',
                'backlog_keys' => [],
            ],

            // ==================== 3. CLUSTER: SUPPORT BIG ====================
            [
                'equip_no' => 'DT-3011',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '07:30',
                'est_hours' => 5.0,
                'ps_type' => '500',
                'wo_no' => 'WO2609-0004',
                'notif_no' => '120004190110',
                'resrv_no' => '5900120',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44021',
                'ppa_ref' => 'PPA-DT3011',
                'dms_ref' => null,
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-002',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'DT-3017',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '08:30',
                'est_hours' => 5.0,
                'ps_type' => '500',
                'wo_no' => '2201889875',
                'notif_no' => '120004190560',
                'resrv_no' => '5900550',
                'av_parts_percent' => 100.0,
                'pap_ref' => 'LAB-44023',
                'ppa_ref' => null,
                'dms_ref' => 'BL-006',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-011',
                'backlog_keys' => ['BL-006'],
            ],
            [
                'equip_no' => 'DT-3019',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '09:30',
                'est_hours' => 5.0,
                'ps_type' => '500',
                'wo_no' => 'WO2609-0020',
                'notif_no' => '120004191020',
                'resrv_no' => '5901120',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => 'BL-011',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-027',
                'backlog_keys' => ['BL-011'],
            ],
            [
                'equip_no' => 'WT-009',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '10:30',
                'est_hours' => 5.0,
                'ps_type' => '500',
                'wo_no' => 'WO2609-0018',
                'notif_no' => '120004191450',
                'resrv_no' => '5901650',
                'av_parts_percent' => 88.0,
                'pap_ref' => 'LAB-44025',
                'ppa_ref' => 'PPA-WT009',
                'dms_ref' => 'BL-009',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-024',
                'backlog_keys' => ['BL-009'],
            ],
            [
                'equip_no' => 'WT-011',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '13:00',
                'est_hours' => 4.5,
                'ps_type' => '500',
                'wo_no' => '2201889882',
                'notif_no' => '120004191890',
                'resrv_no' => '5902100',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => null,
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-008',
                'backlog_keys' => [],
            ],
            [
                'equip_no' => 'ST-002',
                'sub_section' => 'SUPPORT BIG',
                'pic' => 'DERY W',
                'location' => 'KBCT',
                'plan_start_time' => '14:00',
                'est_hours' => 3.5,
                'ps_type' => '250',
                'wo_no' => 'WO2609-0016',
                'notif_no' => '120004192340',
                'resrv_no' => '5902550',
                'av_parts_percent' => 100.0,
                'pap_ref' => null,
                'ppa_ref' => null,
                'dms_ref' => 'BL-008',
                'ppm_ref' => null,
                'ppe_ref' => null,
                'ppc_ref' => null,
                'vis_ref' => 'INSP-023',
                'backlog_keys' => ['BL-008'],
            ]
        ];

        // Seed untuk setiap tanggal target
        foreach ($targetDates as $schedDate) {
            foreach ($scheduleBlueprints as $idx => $bp) {
                $equipNo = $bp['equip_no'];

                // Cari data riil di master_equips
                $equip = MasterEquip::where('equip_no', $equipNo)->first();
                $model = $equip ? $equip->model : 'HEAVY EQUIPMENT';

                // Cari HM riil terkini dari daily_hms
                $latestDailyHm = DailyHm::where('equip_no', $equipNo)
                    ->orderByDesc('tanggal')
                    ->orderByDesc('id')
                    ->value('hm_akhir');
                $currentHm = floatval($latestDailyHm ?: ($equip->last_hm ?? 1000));

                // Cari target HM dari plan_services
                $planService = PlanService::where('equip_no', $equipNo)->first();
                $planHm = $planService ? floatval($planService->next_service_hm) : (ceil($currentHm / 250) * 250);

                // Buat item PS Schedule
                $schedule = PsSchedule::create([
                    'schedule_date'    => $schedDate,
                    'equip_no'         => $equipNo,
                    'code_number'      => $equipNo,
                    'model'            => $model,
                    'current_hm'       => $currentHm,
                    'plan_hm'          => $planHm,
                    'ps_type'          => $bp['ps_type'],
                    'plan_start_date'  => $schedDate,
                    'plan_start_time'  => $bp['plan_start_time'],
                    'est_hours'        => $bp['est_hours'],
                    'sub_section'      => $bp['sub_section'],
                    'pic'              => $bp['pic'],
                    'location'         => $bp['location'] ?: ($equip->location ?? 'KBCT'),
                    'wo_no'            => $bp['wo_no'],
                    'notif_no'         => $bp['notif_no'],
                    'resrv_no'         => $bp['resrv_no'],
                    'av_parts_percent' => $bp['av_parts_percent'],
                    'pap_ref'          => $bp['pap_ref'],
                    'ppa_ref'          => $bp['ppa_ref'],
                    'dms_ref'          => $bp['dms_ref'],
                    'ppm_ref'          => $bp['ppm_ref'],
                    'ppe_ref'          => $bp['ppe_ref'],
                    'ppc_ref'          => $bp['ppc_ref'],
                    'vis_ref'          => $bp['vis_ref'],
                    'status'           => 'SCHEDULED',
                    'created_by'       => 'Planner',
                ]);

                // Bundling Backlog Defect Riil dari tabel backlogs
                if (!empty($bp['backlog_keys'])) {
                    foreach ($bp['backlog_keys'] as $bKey) {
                        $bl = Backlog::where('item_id', $bKey)->orWhere('id', $bKey)->first();
                        $desc = $bl ? $bl->deskripsi_backlog : "Defect {$bKey} pada {$equipNo}";

                        PsScheduleBacklog::create([
                            'ps_schedule_id'   => $schedule->id,
                            'backlog_id'       => $bKey,
                            'wo_no'            => '2201' . rand(700000, 799999),
                            'notif_no'         => '12000' . rand(4180000, 4189999),
                            'resrv_no'         => '53' . rand(70000, 79999),
                            'av_parts_percent' => 100.0,
                            'description'      => $desc,
                            'status'           => 'PENDING',
                        ]);
                    }
                }
            }
        }
    }
}
