<?php

namespace App\Filament\Resources\TargetJamOperasis\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class TargetJamOperasiInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('equip_no')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('section')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('model')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('est_hm')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('next_service_hours_due')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('next_service_type_hm')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('next_service_type')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('next_service_date')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('pm_250')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pm_500')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pm_1000')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pm_2000')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pm_other')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ba_gg')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('oil_fe')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pos')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('plan_year')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('plan_month')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('est_hm_date')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('next_service_hours_due_2')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('next_service_type_2')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('next_service_date_2')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('pm_4000')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('downtime_pm')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('downtime_backlog')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('downtime_midlife')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('downtime_pcr')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
