<?php

namespace App\Filament\Resources\OilSamples\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class OilSampleInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('item_id')
                    ->placeholder('-'),
                TextEntry::make('sample_code')
                    ->placeholder('-'),
                TextEntry::make('equip_no')
                    ->placeholder('-'),
                TextEntry::make('compartment')
                    ->placeholder('-'),
                TextEntry::make('sample_date')
                    ->placeholder('-'),
                TextEntry::make('hm')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('oil_grade')
                    ->placeholder('-'),
                TextEntry::make('rating')
                    ->placeholder('-'),
                TextEntry::make('top_up')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('repair_notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('si')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('al')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('na')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('fe')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('cu')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('cr')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pb')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pq')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('visc_100')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('oxi')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('soot')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('tbn')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('iso_6')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('iso_14')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('water_pct')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('interpretation')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('lab_vendor')
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->placeholder('-'),
                TextEntry::make('created_by')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
